### ISSUE TITLE
Generating snapshot title automatically

### ISSUE THREAD

**Issue by mooreryan** [giacomocavalieri/birdie#12]
I'm not sure if this is actually a good idea or not, but what do you think of a function like `birdie.snap` but that doesn't take a `title` argument?

I've been naming my snaps pretty consistently like this `birdie.snap("module_name.test_function_name")`, because I really don't care about another special snap name other than one specified by the module_name.test_name.  So you could imagine a `birdie` function that generates that name automatically.

Here is what currently goes at the top of the snap:

```
---
version: 1.1.6
title: or_error_test.to_string__error__test
file: ./test/or_error_test.gleam
test_name: to_string__error__test
---
blah blah
```

Given that it "knows" the name of the file and the name of the test, you could imagine using those to generate a default snap title rather than the user presenting one.

Something like this maybe:

`./test/my_module_test.gleam`

```gleam
pub fn some_cool_title__test() { 
  "do something snazzy"
  |> birdie.snap_default()
}
```

and then the generated snap might be something like this:

```
---
version: 1.1.6
title: ./test/my_module_test.some_cool_title__test
file: ./test/my_module_test.gleam
test_name: some_cool_title__test
---
...
```

**Comment by giacomocavalieri** [comment]
Hello! The problem is that, that kind of information is not retrieved when you run the snapshot, but rather when you do the review process by parsing your test modules. In addition the file name cannot always be retrieved 100% of the times.
Since Gleam has no meta programming capabilities there's really no way for me to get the name of the function a snapshot test is defined in* 

* technically I could throw and catch exceptions and by inspecting the stack traces get the function name... but that sounds really hacky and I'm not really considering it a worthwhile solution

**Comment by mooreryan** [comment]
Ah I didn't realize that info didn't come until later, I should have read the code.  Sorry for the noise!

**Comment by giacomocavalieri** [comment]
No problem at all! :)
